version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: test_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_management_app
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: test_management_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    build: .
    container_name: test_management_web
    restart: always
    environment:
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_HOST: db
      DB_NAME: test_management_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: python app.py

volumes:
  db_data:
